/* Compiles engine.c and engine_par.c → four .wasm modules → engine-wasm.js
 * (base64-embedded loader).  Run:  node wasmbuild.js
 * (requires clang with the wasm32 target + wasm-ld).  The generated
 * engine-wasm.js is committed so users don't need clang.
 *
 * Two builds of each module: a baseline one and a SIMD one (auto-vectorised
 * fills).  The loader probes WebAssembly.validate() with a tiny SIMD module
 * and picks the SIMD build only where it is supported; everything else
 * (non-trapping float→int conversions) has been in every major engine since
 * 2021, and any environment that still rejects a module falls back to the
 * JavaScript engines, which are exact too.
 */
"use strict";

var cp = require("child_process");
var fs = require("fs");
var path = require("path");

var dir = __dirname;
var COMMON = "clang --target=wasm32 -O3 -nostdlib -fno-builtin -mnontrapping-fptoint -Wl,--no-entry -Wl,-z,stack-size=65536";
var SINGLE = " -Wl,--export-memory -Wl,--allow-undefined -Wl,--initial-memory=1114112 -Wl,--max-memory=4294901760";
var SHARED = " -matomics -mbulk-memory -Wl,--import-memory -Wl,--shared-memory -Wl,--initial-memory=1114112 -Wl,--max-memory=4294901760";

function build(out, src, flags) {
  cp.execSync(COMMON + flags + " -o " + out + " " + src, { cwd: dir, stdio: "inherit" });
  return fs.readFileSync(path.join(dir, out));
}

var wasm = build("engine.wasm", "engine.c", SINGLE);
var wasmSimd = build("engine_simd.wasm", "engine.c", SINGLE + " -msimd128");
var par = null, parSimd = null;
try {
  par = build("engine_par.wasm", "engine_par.c", SHARED);
  parSimd = build("engine_par_simd.wasm", "engine_par.c", SHARED + " -msimd128");
} catch (e) {
  console.warn("engine_par.wasm not built (" + e.message + ") — multi-core will use the JS kernels");
}
var b64 = function (buf) { return buf ? buf.toString("base64") : ""; };

var out = [
  "/* GENERATED by wasmbuild.js from engine.c and engine_par.c — do not edit by hand.",
  " * Near-native Lucy_Hedgehog prime counting as base64 WebAssembly modules",
  " * (baseline + SIMD builds, single-thread + shared-memory kernels).",
  " * Loads in browsers, Web Workers and Node; ~" + ((wasm.length + wasmSimd.length + (par ? par.length : 0) + (parSimd ? parSimd.length : 0)) / 1024).toFixed(1) + " KB of code. */",
  "(function (root, factory) {",
  "  \"use strict\";",
  "  if (typeof module === \"object\" && module.exports) module.exports = factory();",
  "  else root.NthPrimeWasm = factory();",
  "})(typeof self !== \"undefined\" ? self : this, function () {",
  "  \"use strict\";",
  "  var B64 = \"" + b64(wasm) + "\";",
  "  var B64_SIMD = \"" + b64(wasmSimd) + "\";",
  "  var PAR_B64 = \"" + b64(par) + "\";",
  "  var PAR_B64_SIMD = \"" + b64(parSimd) + "\";",
  "  var SEG = " + SEG_VALUE() + "; // sweep segment length compiled into both modules",
  "  function decode(s) {",
  "    if (typeof atob === \"function\") {",
  "      var bin = atob(s);",
  "      var bytes = new Uint8Array(bin.length);",
  "      for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);",
  "      return bytes;",
  "    }",
  "    return new Uint8Array(Buffer.from(s, \"base64\"));",
  "  }",
  "  // does this engine accept the SIMD proposal?  (the probe is a module whose",
  "  // only function returns an i32x4.splat — the standard wasm-feature-detect test)",
  "  function detectSimd() {",
  "    if (typeof WebAssembly === \"undefined\") return false;",
  "    try {",
  "      return WebAssembly.validate(new Uint8Array([0, 97, 115, 109, 1, 0, 0, 0, 1, 5, 1, 96, 0, 1, 123, 3, 2, 1, 0, 10, 10, 1, 8, 0, 65, 0, 253, 15, 253, 98, 11]));",
  "    } catch (e) { return false; }",
  "  }",
  "  var simd = detectSimd();",
  "  var cached = null;",
  "  var progressCb = null;",
  "  function instantiate(bytes) {",
  "    var mod = new WebAssembly.Module(bytes);",
  "    var inst = new WebAssembly.Instance(mod, { env: { progress: function (p, r) {",
  "      if (progressCb) progressCb(Number(p) / Number(r));",
  "    } } });",
  "    return { exports: inst.exports, memory: inst.exports.memory, simd: simd };",
  "  }",
  "  function init() {",
  "    if (cached) return cached;",
  "    if (typeof WebAssembly === \"undefined\" || typeof BigInt === \"undefined\") return null;",
  "    try { cached = instantiate(decode(simd ? B64_SIMD : B64)); }",
  "    catch (e) {",
  "      try { cached = instantiate(decode(B64)); cached.simd = false; simd = false; }",
  "      catch (e2) { cached = null; }",
  "    }",
  "    return cached;",
  "  }",
  "  function setProgress(cb) { progressCb = cb; }",
  "  return {",
  "    init: init, setProgress: setProgress, SEG: SEG,",
  "    get simd() { return simd; },",
  "    get parB64() { return simd ? PAR_B64_SIMD : PAR_B64; },",
  "    parB64Plain: PAR_B64,",
  "    generated: true",
  "  };",
  "});",
  ""
].join("\n");

function SEG_VALUE() {
  // read the compiled-in segment length from the module (both share it)
  var inst = new WebAssembly.Instance(new WebAssembly.Module(wasm), { env: { progress: function () {} } });
  return inst.exports.seg();
}

fs.writeFileSync(path.join(dir, "engine-wasm.js"), out);
console.log("wrote engine.wasm (" + wasm.length + " B), engine_simd.wasm (" + wasmSimd.length + " B)" +
  (par ? ", engine_par.wasm (" + par.length + " B), engine_par_simd.wasm (" + parSimd.length + " B)" : "") + " and engine-wasm.js");
