/* Compiles engine.c → engine.wasm → engine-wasm.js (base64-embedded loader).
 * Run:  node wasmbuild.js     (requires clang with wasm32 target + wasm-ld)
 * The generated engine-wasm.js is committed so users don't need clang.
 */
"use strict";

var cp = require("child_process");
var fs = require("fs");
var path = require("path");

var dir = __dirname;
var cmd = [
  "clang", "--target=wasm32", "-O3", "-nostdlib",
  "-Wl,--no-entry",
  "-Wl,--export-memory",
  "-Wl,--allow-undefined",
  "-Wl,--initial-memory=1114112",      // 17 pages; grown at runtime as needed
  "-Wl,--max-memory=4294901760",       // 65535 pages ≈ 4 GiB (wasm32 ceiling)
  "-Wl,-z,stack-size=65536",
  "-o", "engine.wasm", "engine.c"
].join(" ");

cp.execSync(cmd, { cwd: dir, stdio: "inherit" });

// thread-safe variant for the multi-core engine: same kernels over ONE shared memory
var cmdPar = [
  "clang", "--target=wasm32", "-O3", "-nostdlib", "-matomics", "-mbulk-memory",
  "-Wl,--no-entry",
  "-Wl,--import-memory",
  "-Wl,--shared-memory",
  "-Wl,--initial-memory=1114112",
  "-Wl,--max-memory=4294901760",
  "-Wl,-z,stack-size=65536",
  "-o", "engine_par.wasm", "engine_par.c"
].join(" ");
var parB64 = "";
try {
  cp.execSync(cmdPar, { cwd: dir, stdio: "inherit" });
  parB64 = fs.readFileSync(path.join(dir, "engine_par.wasm")).toString("base64");
} catch (e) {
  console.warn("engine_par.wasm not built (" + e.message + ") — multi-core will use the JS kernels");
}

var wasm = fs.readFileSync(path.join(dir, "engine.wasm"));
var b64 = wasm.toString("base64");

var out = [
  "/* GENERATED by wasmbuild.js from engine.c — do not edit by hand.",
  " * Near-native Lucy_Hedgehog prime counting as a base64 WebAssembly module.",
  " * Loads in browsers, Web Workers and Node; ~" + (wasm.length / 1024).toFixed(1) + " KB. */",
  "(function (root, factory) {",
  "  \"use strict\";",
  "  if (typeof module === \"object\" && module.exports) module.exports = factory();",
  "  else root.NthPrimeWasm = factory();",
  "})(typeof self !== \"undefined\" ? self : this, function () {",
  "  \"use strict\";",
  "  var B64 = \"" + b64 + "\";",
  "  var PAR_B64 = \"" + parB64 + "\";",
  "  var cached = null;",
  "  function decode(s) {",
  "    if (typeof atob === \"function\") {",
  "      var bin = atob(s);",
  "      var bytes = new Uint8Array(bin.length);",
  "      for (var i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);",
  "      return bytes;",
  "    }",
  "    return new Uint8Array(Buffer.from(s, \"base64\"));",
  "  }",
  "  var progressCb = null;",
  "  function init() {",
  "    if (cached) return cached;",
  "    if (typeof WebAssembly === \"undefined\" || typeof BigInt === \"undefined\") return null;",
  "    try {",
  "      var mod = new WebAssembly.Module(decode(B64));",
  "      var inst = new WebAssembly.Instance(mod, { env: { progress: function (p, r) {",
  "        if (progressCb) progressCb(Number(p) / Number(r));",
  "      } } });",
  "      cached = { exports: inst.exports, memory: inst.exports.memory };",
  "    } catch (e) {",
  "      cached = null;",
  "    }",
  "    return cached;",
  "  }",
  "  function setProgress(cb) { progressCb = cb; }",
  "  return { init: init, setProgress: setProgress, parB64: PAR_B64, generated: true };",
  "});",
  ""
].join("\n");

fs.writeFileSync(path.join(dir, "engine-wasm.js"), out);
console.log("wrote engine.wasm (" + wasm.length + " B) and engine-wasm.js");
